### ISSUE TITLE
JAVA_HOME is hardcoded in makefile

### ISSUE THREAD

**Issue by dhasenan** [funkwerk/antlr-d#6]
`JAVA_HOME` should generally be set before calling `make`, and the correct path is system-dependent. The makefile hardcodes it to `/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0`, which is not the correct path on my system (default openjdk8 install on Ubuntu 18.04).

**Comment by BayernEV** [comment]
Yes, you are right. I will remove the related path restriction from Makefile with the next release soon and add a comment.
