### ISSUE TITLE
Visitors don't work

### ISSUE THREAD

**Issue by dhasenan** [funkwerk/antlr-d#7]
I'm looking into fixing it.

**Comment by dhasenan** [comment]
Doing this in the same manner as Java is...awkward. The `accept` function would be defined as:

```D
abstract T accept(T)(ExprVisitor!T visitor);
// in each Context class:
override T accept(T)(ExprVisitor!T visitor) { return visitor.visit(this); }
```

The problem is that templated functions can't be virtual.

There are three ways I can address this:

1. Remove the visitor from the Context class tree entirely.
2. All `visit` methods return `Variant`.
3. All `visit` methods return void.

I'm leaning heavily toward the first option.

### Move visitors outside the Context class

The `visit(ParseContext)` method looks like:

```D
if (ctx.classinfo is ExprContext.classinfo) return visit(cast(ExprContext)ctx);
if (ctx.classinfo is ProgContext.classinfo) return visit(cast(ProgContext)ctx);
assert(false, "unrecognized type");
```

This incurs a cost that's linear in the number of Context types. It could be replaced with an associative array mapping a classinfo to a handler delegate, though:

```D
static T delegate(Visitor, ParseTree)[ClassInfo] handlers;
static this()
{
  handlers = [
    ExprContext.classinfo: (v, p) => v.visit(cast(ExprContext)p),
    ProgContext.classinfo: (v, p) => v.visit(cast(ProgContext)p),
  ];
}
T visit(ParseTree p)
{
  if (auto handler = p.classinfo in handlers)
   return handler(this, p);
  assert(false);
}
```

I'm guessing the pile-of-equality-tests variant is faster if you've only got ten types and the AA version is faster if you have a few hundred, but no clue where the transition point is.

### All visit/accept methods return Variant

If all `visit` and `accept` methods return a `std.variant.Variant`, we don't need to template `accept`. However, there's a constant amount of runtime overhead.

`BaseVisitor` can contain convenience wrappers that return a specific type, automatically converting to and from `Variant`:

```D
class ExprBaseVisitor(T) : ExprVisitor
{
  override Variant visit(ExprParser.ExprContext ctx)
  {
    return Variant(visitImpl(ctx));
  }
  protected abstract T visitImpl(ExprParser.ExprContext ctx);
}
```

This could also be done with a wrapper instead of inheritance.

### All visit/accept methods return void

As before. `BaseVisitor` stores the last value returned from a `visit` function in a field instead of going through `Variant`:

```D
class ExprBaseVisitor(T) : ExprVisitor
{
  private T lastValue;
  override void visit(ExprParser.ExprContext ctx)
  {
    lastValue = visitImpl(ctx);
  }
  protected abstract T visitImpl(ExprParser.ExprContext ctx);
}
```

This avoids the cost of boxing and unboxing stuff, but it means your visitors are not reentrant.

**Comment by BayernEV** [comment]
Your Variant proposal is now in the branch _visitor_with_variant_, but unit tests for visitors under work.
